# Use the official lightweight Node.js 12 image.
# https://hub.docker.com/_/node
FROM node:12.16.1-alpine

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying this separately prevents re-running npm install on every code change.
COPY . .

# Install production dependencies.
RUN npm install

RUN npm run build 

# Copy local code to the container image.
# COPY . ./

# Run the web service on container startup.
# CMD [ "npm", "start" ]

FROM nginx

# COPY nginx/conf/nginx.conf /etc/nginx/conf.d/default.conf
# COPY nginx/nginx.conf /etc/nginx/nginx.conf

COPY --from=0 /usr/src/app/dist/ /usr/share/nginx/html
