apiVersion: v1
kind: ConfigMap
metadata:
  name: managed-web-app-dockerfile
  namespace: default
data:
  "Dockerfile": |-
    FROM node:12.16.1-alpine
    WORKDIR /usr/src/app
    COPY . .
    RUN npm install
    RUN npm run build
    FROM nginx
    COPY --from=0 /usr/src/app/dist/ /usr/share/nginx/html
