apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: tekton-kn-sample-01
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: tekton-knative-git
  params:
    - name: pathToContext
      value: "src"
    - name: pathToYamlFile
      value: "managed-web-app-deployment"
    - name: imageUrl
      value: "registry.cn-hangzhou.aliyuncs.com/abcpingtaitac/commemorate-front"
    - name: imageTag
      value: "1.1"
  serviceAccount: pipeline-account
