apiVersion: v1
kind: Service
metadata:
  name: commemorate-front-service
spec:
  selector:
    app: commemorate-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
